apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: "slave"
    jenkins/jenkins-jenkins-slave: "true"
  name: jnlp-slave
spec:
  hostNetwork: false
  nodeSelector:
    beta.kubernetes.io/os: "linux"
  restartPolicy: "Never"
  securityContext: {}
  serviceAccount: "default"
  containers:
  - name: "jnlp"
    image: "jenkins/jnlp-slave:3.27-1"
    resources:
     limits:
       memory: "2Gi"
       cpu: "512m"
     requests:
       memory: "512Mi"
       cpu: "512m"
    workingDir: "/home/jenkins/agent"   
    securityContext:
      privileged: false
    tty: false
    env:
      - name: "JENKINS_URL"
        value: "http://jenkins.jenkins.svc.cluster.local:8080"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - name: docker
    image: docker:19.03.3-dind
    securityContext:
      privileged: true
    resources:
     limits:
       memory: "512Gi"
       cpu: "512m"
     requests:
       memory: "512Mi"
       cpu: "512m"  
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""  
  - name: kubectl
    image: achlanevenson/k8s-kubectl:v1.8.8   
    command: ['cat']
    tty: true
    

  
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"

