apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: "slave"
    jenkins/jenkins-jenkins-slave: "true"
  name: jnlp-slave
spec:
  hostNetwork: false
  nodeSelector:
    beta.kubernetes.io/os: "linux"
  restartPolicy: "Never"
  securityContext: {}
  serviceAccount: "default"
  containers:
  - name: docker
    image: docker:stable-dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""  
  - name: helm
    image: lachlanevenson/k8s-helm:v2.16.1  
    tty: true
    command:
      - "cat"
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"

